dataBase=
[
{id :0, stock: true, name: "RESIDENTIAL NEMESIS", price: 38, amount: 0, img:1,},
{id :1, stock: true, name: "THIS MIGHT BE A COVER", price: 38, amount: 0, img:2,},
{id :2, stock: true, name: "EARTHQUAKE", price: 38, amount: 0, img:3,},
{id :3, stock: false, name: "WIREFRAME+AUSTRIA3", price: 38, amount: 0, img:4,},
{id :4, stock: true, name: "ICE AGE COMIG", price: 38, amount: 0, img:5,},
{id :5, stock: true, name: "GET OUT BEFORE SATURDAY", price: 38, amount: 0, img:6,},
{id :6, stock: true, name: "HOTELS AND A GLACIER", price: 38, amount: 0, img:7,},
{id :7, stock: true, name: "TARGET 80S LANDSCAPE", price: 38, amount: 0, img:8,},
{id :8, stock: true, name: "COCAINE DISKO ALL YOU LIKE", price: 38, amount: 0, img:9,},
{id :9, stock: false, name: "ICE AGE COMING ICE AGE COMING", price: 38, amount: 0, img:10,},
{id :10, stock: true, name: "27 WOODEN WOODS", price: 38, amount: 0, img:11,},
{id :11, stock: true, name: "GMT LAND BEING INVADED POINTY", price: 38, amount: 0, img:12,},
{id :12, stock: true, name: "BURNING CITY GOOD VERSION", price: 38, amount: 0, img:13,},
{id :13, stock: true, name: "LAND OF FREEDOM™", price: 38, amount: 0, img:14,},
{id :14, stock: true, name: "TWO TOWERS", price: 38, amount: 0, img:15,},
{id :15, stock: false, name: "ITS GROOVY BABY", price: 38, amount: 0, img:16,},
{id :16, stock: true, name: "WILL YOU COME BACK TO ME", price: 38, amount: 0, img:17,},
{id :17, stock: true, name: "MERGER", price: 38, amount: 0, img:18,},
{id :18, stock: true, name: "REALLY HAPPENING", price: 38, amount: 0, img:19,},
{id :19, stock: true, name: "TARGET LAND", price: 38, amount: 0, img:20,},
{id :20, stock: true, name: "MINOS WALL I", price: 38, amount: 0, img:21,},
{id :21, stock: false, name: "RMINOS WALL II", price: 38, amount: 0, img:22,},
{id :22, stock: true, name: "MINOS WALL III", price: 38, amount: 0, img:23,},
]